"""empty message

Revision ID: 0df56512b7ba
Revises: 
Create Date: 2023-12-03 01:26:36.373831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df56512b7ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('charging_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('charger_types', sa.String(length=255), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('pricing', sa.String(length=255), nullable=False),
    sa.Column('opening_hours', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charging_station')
    op.drop_table('user')
    # ### end Alembic commands ###
